name: FreshersHunt Scraper

on:
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Run Scraper
        run: java -jar target/*.jar